language: generic
sudo: false

addons:
  apt:
    packages:
      - luarocks

before_install:
  - luarocks install --local busted

install:
  - luarocks make --local  rockspecs/panluna-scm-0.rockspec

script:
  - ~/.luarocks/bin/busted --output=TAP

notifications:
  email:
    on_success: change
    on_failure: always
