language: generic
sudo: false

env:
  - PANDOC_VERSION=1.19.1-1

addons:
  apt:
    packages:
      - luarocks

before_install:
  # install luarocks
  - luarocks install --local busted

  # install pandoc
  - DOWNLOAD_URL="https://github.com/jgm/pandoc/releases/download"
  - mkdir -p ${HOME}/.local
  - |
    travis_retry curl --location --silent \
      ${DOWNLOAD_URL}/${PANDOC_VERSION%-*}/pandoc-${PANDOC_VERSION}-amd64.deb \
      -o /tmp/pandoc.deb
  - ar p /tmp/pandoc.deb data.tar.gz | tar xvz --strip-components 2 -C $HOME/.local/

  # Set path to include pandoc and luarock executables
  - PATH="${HOME}/.luarocks/bin:$PATH"
  - PATH="${HOME}/.local/bin:$PATH"

install:
  - luarocks make --local  rockspecs/panluna-scm-0.rockspec

script:
  - busted --output=TAP

notifications:
  email:
    on_success: change
    on_failure: always
